"""
Multi-Agent Collaboration System.
Splits NexusAgent into specialist agents that collaborate:
  - PlannerAgent → breaks complex tasks into steps, delegates to specialists
  - DataAgent   → SQL + data analysis
  - DocAgent    → RAG + document reasoning
  - SynthesisAgent → combines results from all agents into a final answer

Usage:
  "Analyze our Q3 docs, query the DB for the same period, then write a board summary"
  → PlannerAgent breaks it down → DataAgent + DocAgent work in parallel → SynthesisAgent combines
"""
from __future__ import annotations

import time
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from enum import Enum

from loguru import logger

from config.llm_config import get_llm


# ── Agent Message Protocol ───────────────────────────────────────────────────
class AgentRole(str, Enum):
    PLANNER = "planner"
    DATA = "data"
    DOC = "doc"
    SYNTHESIS = "synthesis"


@dataclass
class AgentMessage:
    """Message passed between agents."""
    sender: AgentRole
    content: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    status: str = "success"  # success | error | partial


@dataclass
class AgentResult:
    """Result from a specialist agent."""
    agent_name: str
    task: str
    result: str
    data: Optional[Any] = None
    error: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


# ── Task Plan Structure ──────────────────────────────────────────────────────
@dataclass
class TaskStep:
    """A single step in a task plan."""
    step_id: int
    description: str
    assigned_agent: AgentRole
    depends_on: List[int] = field(default_factory=list)
    input_context: str = ""
    status: str = "pending"  # pending | running | done | error


@dataclass
class TaskPlan:
    """Complete plan generated by PlannerAgent."""
    original_query: str
    steps: List[TaskStep]
    execution_order: List[List[int]]  # groups of step_ids that can run in parallel
    summary: str = ""


# ── PlannerAgent ─────────────────────────────────────────────────────────────
class PlannerAgent:
    """
    Breaks complex user requests into a structured plan.
    Decides which specialist agents to use and in what order.
    """

    SYSTEM_PROMPT = """You are the PlannerAgent, an expert task decomposition agent.
Your job is to break complex user requests into ordered steps, assigning each step to the right specialist.

Available specialists:
- DataAgent: Queries the database, runs SQL analysis, generates data insights, creates charts
- DocAgent: Searches documents, answers questions from uploaded files, compares documents, finds contradictions
- (Synthesis is automatic — combines all results at the end)

Rules:
1. If the request needs BOTH data and documents, plan parallel execution
2. If one step depends on another, order them sequentially
3. Be specific in step descriptions — tell each agent exactly what to do
4. Maximum 5 steps per plan
5. Include a "final_summary" step that describes how to combine results

Respond in this EXACT format:

PLAN_SUMMARY: <one sentence describing the overall plan>

STEP 1: <description>
AGENT: <DataAgent|DocAgent>
DEPENDS_ON: <step numbers or "none">

STEP 2: <description>
AGENT: <DataAgent|DocAgent>
DEPENDS_ON: <step numbers or "none">

... (more steps as needed)

FINAL: <how to combine all results into a final answer>"""

    def plan(self, query: str) -> TaskPlan:
        """Generate a task plan from a user query."""
        try:
            llm = get_llm()
            response = llm.invoke(self.SYSTEM_PROMPT + f"\n\nUSER REQUEST: {query}\n\nPLAN:")
            return self._parse_plan(query, response)
        except Exception as e:
            logger.error(f"[PlannerAgent] Planning failed: {e}")
            # Fallback: single-step plan with the most likely agent
            return self._fallback_plan(query)

    def _parse_plan(self, query: str, response: str) -> TaskPlan:
        """Parse LLM response into a TaskPlan."""
        steps = []
        summary = ""
        final_summary = ""

        lines = response.strip().split("\n")
        current_step = None

        for line in lines:
            line = line.strip()
            if line.upper().startswith("PLAN_SUMMARY:"):
                summary = line.split(":", 1)[1].strip()
            elif line.upper().startswith("STEP"):
                # Parse step number and description
                parts = line.split(":", 1)
                if len(parts) == 2:
                    step_num_match = parts[0].upper().replace("STEP", "").strip()
                    try:
                        step_id = int(step_num_match)
                    except ValueError:
                        step_id = len(steps) + 1
                    current_step = {
                        "step_id": step_id,
                        "description": parts[1].strip(),
                        "agent": None,
                        "depends_on": [],
                    }
            elif line.upper().startswith("AGENT:") and current_step:
                agent_str = line.split(":", 1)[1].strip().lower()
                if "data" in agent_str:
                    current_step["agent"] = AgentRole.DATA
                elif "doc" in agent_str:
                    current_step["agent"] = AgentRole.DOC
                else:
                    current_step["agent"] = AgentRole.DATA  # default
            elif line.upper().startswith("DEPENDS_ON:") and current_step:
                dep_str = line.split(":", 1)[1].strip().lower()
                if dep_str != "none":
                    try:
                        current_step["depends_on"] = [
                            int(x.strip()) for x in dep_str.replace("step", "").split(",")
                            if x.strip().isdigit()
                        ]
                    except ValueError:
                        current_step["depends_on"] = []
                    steps.append(TaskStep(**current_step))
                    current_step = None
            elif line.upper().startswith("FINAL:"):
                final_summary = line.split(":", 1)[1].strip()

        if not steps:
            return self._fallback_plan(query)

        # Compute execution order (topological sort for parallel groups)
        execution_order = self._compute_execution_order(steps)

        return TaskPlan(
            original_query=query,
            steps=steps,
            execution_order=execution_order,
            summary=summary or f"Plan for: {query}",
        )

    def _compute_execution_order(self, steps: List[TaskStep]) -> List[List[int]]:
        """Group steps into parallel execution waves."""
        if not steps:
            return []

        # Simple approach: group by dependency depth
        step_map = {s.step_id: s for s in steps}
        visited = set()
        order = []

        def get_depth(step_id: int) -> int:
            if step_id in visited:
                return 0
            step = step_map.get(step_id)
            if not step or not step.depends_on:
                return 0
            visited.add(step_id)
            return 1 + max(get_depth(d) for d in step.depends_on if d in step_map)

        depths = {}
        for s in steps:
            visited.clear()
            depths[s.step_id] = get_depth(s.step_id)

        # Group by depth
        max_depth = max(depths.values()) if depths else 0
        for d in range(max_depth + 1):
            group = [sid for sid, depth in depths.items() if depth == d]
            if group:
                order.append(sorted(group))

        return order

    def _fallback_plan(self, query: str) -> TaskPlan:
        """Create a simple fallback plan."""
        # Default: try both agents in parallel
        steps = [
            TaskStep(step_id=1, description=f"Analyze data related to: {query}",
                      assigned_agent=AgentRole.DATA),
            TaskStep(step_id=2, description=f"Search documents related to: {query}",
                      assigned_agent=AgentRole.DOC),
        ]
        return TaskPlan(
            original_query=query,
            steps=steps,
            execution_order=[[1, 2]],
            summary=f"Parallel analysis for: {query}",
        )

    def should_use_multi_agent(self, query: str) -> bool:
        """Decide if a query needs multi-agent collaboration."""
        lower = query.lower()

        # Explicit multi-agent triggers
        multi_triggers = [
            "and then", "also", "both", "combine", "together",
            "analyze", "compare", "cross-reference", "correlate",
            "docs", "documents", "database", "data", "report",
        ]

        # Check for multiple intent indicators
        has_doc_intent = any(kw in lower for kw in (
            "doc", "document", "file", "report", "policy", "pdf",
            "read", "uploaded", "compare", "contradict",
        ))
        has_data_intent = any(kw in lower for kw in (
            "data", "query", "database", "sql", "analyze", "sales",
            "revenue", "region", "product", "customer", "chart",
            "metric", "trend", "number", "figure",
        ))

        if has_doc_intent and has_data_intent:
            return True

        # Check for sequential actions
        if any(trigger in lower for trigger in multi_triggers):
            if has_doc_intent or has_data_intent:
                return True

        # Long/complex queries often benefit from multi-agent
        if len(query.split()) > 20:
            return True

        return False


# ── DataAgent ────────────────────────────────────────────────────────────────
class DataAgent:
    """
    Specialist for SQL, data analysis, and database queries.
    Wraps the existing SQL executor with enhanced analysis.
    """

    def execute(self, task: str, context: str = "") -> AgentResult:
        """Execute a data analysis task."""
        try:
            from sql_agent.executor import execute_query
            from report_generator.chart_selector import select_chart_type
            from report_generator.chart_builder import build_chart

            logger.info(f"[DataAgent] Executing: {task[:80]}")

            # Run the query
            sql_result = execute_query(task, log_to_audit=False)

            if not sql_result.get("success"):
                return AgentResult(
                    agent_name="DataAgent",
                    task=task,
                    result=f"Query failed: {sql_result.get('error', 'unknown error')}",
                    error=sql_result.get("error"),
                )

            df = sql_result.get("dataframe")
            explanation = sql_result.get("explanation", "")

            # Generate chart if data is suitable
            chart_info = ""
            try:
                if df is not None and not getattr(df, "empty", True):
                    chart_type, _ = select_chart_type(df, task)
                    fig, png_path = build_chart(df, chart_type, task[:50])
                    chart_info = f"\nChart generated: {png_path}"
            except Exception as e:
                logger.warning(f"[DataAgent] Chart generation failed: {e}")

            result_text = f"DATA ANALYSIS RESULT:\n{explanation}\n{chart_info}"

            return AgentResult(
                agent_name="DataAgent",
                task=task,
                result=result_text,
                data=df,
                metadata={
                    "sql_query": sql_result.get("query_used", ""),
                    "row_count": len(df) if df is not None else 0,
                    "explanation": explanation,
                },
            )

        except Exception as e:
            logger.error(f"[DataAgent] Execution failed: {e}")
            return AgentResult(
                agent_name="DataAgent",
                task=task,
                result="",
                error=str(e),
            )


# ── DocAgent ─────────────────────────────────────────────────────────────────
class DocAgent:
    """
    Specialist for document search, RAG, and cross-document reasoning.
    Uses the multi-document RAG system.
    """

    def execute(self, task: str, context: str = "") -> AgentResult:
        """Execute a document analysis task."""
        try:
            from rag.multi_document_rag import multi_doc_retrieve

            logger.info(f"[DocAgent] Executing: {task[:80]}")

            result = multi_doc_retrieve(task)

            answer = result.get("answer", "")
            sources = result.get("sources_used", [])

            sources_text = ""
            if sources:
                sources_text = f"\n\nSources consulted: {', '.join(sources)}"

            citations = result.get("citations", [])
            citation_text = ""
            if citations:
                citation_lines = []
                for c in citations[:5]:
                    citation_lines.append(
                        f"- {c.get('source', '?')} (page {c.get('page', '?')}, "
                        f"confidence: {c.get('confidence', 0):.0%})"
                    )
                citation_text = "\n\nCitations:\n" + "\n".join(citation_lines)

            result_text = f"DOCUMENT ANALYSIS RESULT:\n{answer}{sources_text}{citation_text}"

            return AgentResult(
                agent_name="DocAgent",
                task=task,
                result=result_text,
                metadata={
                    "sources_used": sources,
                    "citations": citations,
                    "mode": result.get("mode", "general"),
                    "is_multi_doc": result.get("is_multi_doc", False),
                },
            )

        except Exception as e:
            logger.error(f"[DocAgent] Execution failed: {e}")
            return AgentResult(
                agent_name="DocAgent",
                task=task,
                result="",
                error=str(e),
            )


# ── SynthesisAgent ───────────────────────────────────────────────────────────
class SynthesisAgent:
    """
    Combines results from multiple specialist agents into a coherent final answer.
    """

    def synthesize(self, query: str, plan: TaskPlan,
                    results: Dict[int, AgentResult]) -> str:
        """Synthesize all agent results into a final answer."""
        if not results:
            return "No analysis results available."

        # Build synthesis context
        context_parts = []
        for step in plan.steps:
            result = results.get(step.step_id)
            if result and result.status == "success":
                context_parts.append(
                    f"### {result.agent_name.upper()} — Step {step.step_id}: {step.description}\n"
                    f"{result.result}"
                )
            elif result and result.error:
                context_parts.append(
                    f"### {result.agent_name.upper()} — Step {step.step_id}: {step.description}\n"
                    f"ERROR: {result.error}"
                )

        context = "\n\n".join(context_parts)

        try:
            llm = get_llm()
            prompt = f"""You are the SynthesisAgent. Combine the following analysis results into a clear, comprehensive answer.

ORIGINAL QUESTION: {query}

ANALYSIS RESULTS:
{context[:6000]}

Provide a well-structured answer that:
1. Directly answers the original question
2. Incorporates key findings from all specialists
3. Highlights the most important insights
4. Notes any limitations or data gaps

SYNTHESIZED ANSWER:"""

            return llm.invoke(prompt).strip()

        except Exception as e:
            logger.error(f"[SynthesisAgent] Synthesis failed: {e}")
            # Fallback: just concatenate results
            return f"Synthesis error. Raw results:\n\n{context}"


# ── Multi-Agent Orchestrator ─────────────────────────────────────────────────
class MultiAgentOrchestrator:
    """
    Coordinates specialist agents to execute a plan.
    Handles parallel execution, dependency management, and error recovery.
    """

    def __init__(self):
        self.planner = PlannerAgent()
        self.data_agent = DataAgent()
        self.doc_agent = DocAgent()
        self.synthesizer = SynthesisAgent()

    def execute(self, query: str) -> Dict[str, Any]:
        """
        Full multi-agent execution pipeline:
        1. Planner creates the task plan
        2. Specialists execute in parallel/sequence as planned
        3. Synthesis combines all results

        Returns:
            {
              answer: str,
              plan: TaskPlan,
              agent_results: Dict[int, AgentResult],
              agents_used: List[str],
              duration_ms: int,
            }
        """
        start = time.time()
        logger.info(f"[MultiAgent] Starting execution for: {query[:100]}")

        # Step 1: Plan
        plan = self.planner.plan(query)
        logger.info(f"[MultiAgent] Plan: {plan.summary} ({len(plan.steps)} steps)")

        # Step 2: Execute steps in order (with parallelism within each wave)
        all_results: Dict[int, AgentResult] = {}

        for wave in plan.execution_order:
            wave_results = self._execute_wave(wave, plan.steps, all_results)
            all_results.update(wave_results)

        # Step 3: Synthesize
        final_answer = self.synthesizer.synthesize(query, plan, all_results)

        duration_ms = int((time.time() - start) * 1000)
        agents_used = list(set(
            r.agent_name for r in all_results.values() if r.status == "success"
        ))

        logger.info(
            f"[MultiAgent] Complete. {len(agents_used)} agents used, "
            f"{duration_ms}ms"
        )

        return {
            "answer": final_answer,
            "plan": plan,
            "agent_results": all_results,
            "agents_used": agents_used,
            "duration_ms": duration_ms,
        }

    def _execute_wave(self, step_ids: List[int],
                       steps: List[TaskStep],
                       completed: Dict[int, AgentResult]) -> Dict[int, AgentResult]:
        """Execute a wave of steps (can be parallel)."""
        results = {}
        step_map = {s.step_id: s for s in steps}

        for step_id in step_ids:
            step = step_map.get(step_id)
            if not step:
                continue

            # Build input context from completed dependencies
            input_context = ""
            for dep_id in step.depends_on:
                dep_result = completed.get(dep_id)
                if dep_result and dep_result.status == "success":
                    input_context += f"\n[Step {dep_id} result: {dep_result.result[:500]}]"

            # Execute
            result = self._execute_step(step, input_context)
            results[step_id] = result

        return results

    def _execute_step(self, step: TaskStep, context: str) -> AgentResult:
        """Execute a single step with the assigned agent."""
        if step.assigned_agent == AgentRole.DATA:
            return self.data_agent.execute(step.description, context)
        elif step.assigned_agent == AgentRole.DOC:
            return self.doc_agent.execute(step.description, context)
        else:
            return AgentResult(
                agent_name="Unknown",
                task=step.description,
                result="",
                error=f"Unknown agent role: {step.assigned_agent}",
            )


# ── Module-level singleton ───────────────────────────────────────────────────
_orchestrator = None


def get_orchestrator() -> MultiAgentOrchestrator:
    global _orchestrator
    if _orchestrator is None:
        _orchestrator = MultiAgentOrchestrator()
    return _orchestrator


def run_multi_agent(query: str) -> Dict[str, Any]:
    """Convenience function to run multi-agent collaboration."""
    orchestrator = get_orchestrator()
    return orchestrator.execute(query)


def multi_agent_node(state):
    """Re-export for graph.py imports."""
    from orchestrator.nodes import multi_agent_node as _node
    return _node(state)
