"""
AI node implementations — LLM Prompt, Summarize, Generate Report, Classify.
"""
from __future__ import annotations
from typing import Dict, Any
from loguru import logger


def run_llm_prompt(config: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:
    prompt_template = config.get("prompt", "Summarize: {input}")
    max_words = config.get("max_words", 0)
    model_override = config.get("model", "default")

    prev_output = str(ctx.get("output", ""))
    df_text = ctx.get("_df_text", "")
    data_block = df_text if df_text else prev_output

    prompt = prompt_template.replace("{input}", data_block[:3000])

    try:
        from config.llm_config import get_llm
        llm = get_llm()

        if max_words and max_words > 0:
            prompt += f"\n\nKeep response under {max_words} words."

        response = llm.invoke(prompt).strip()
        ctx["output"] = response
        logger.info(f"[AI] llm_prompt → {len(response)} chars")
    except Exception as e:
        ctx["output"] = f"LLM error: {e}"

    return ctx


def run_summarize(config: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:
    style = config.get("style", "bullet_points")
    max_points = config.get("max_points", 5)
    data = str(ctx.get("output", ""))
    df_text = ctx.get("_df_text", "")
    source = df_text if df_text else data

    style_prompts = {
        "bullet_points": f"Summarize in exactly {max_points} bullet points (use • prefix):\n\n{{data}}",
        "paragraph": "Write a 2-3 sentence paragraph summarizing:\n\n{data}",
        "executive": "Write a 3-sentence executive summary. Start with the most important finding:\n\n{data}",
        "one_line": "Summarize in ONE sentence:\n\n{data}",
    }
    prompt = style_prompts.get(style, style_prompts["bullet_points"]).replace("{data}", source[:3000])

    try:
        from config.llm_config import get_llm
        llm = get_llm()
        response = llm.invoke(prompt).strip()
        ctx["output"] = response
        logger.info(f"[AI] summarize ({style}) → {len(response)} chars")
    except Exception as e:
        ctx["output"] = f"Summarize error: {e}"

    return ctx


def run_generate_report(config: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:
    title = config.get("title", "Workflow Report")
    include_chart = config.get("include_chart", True)
    chart_type_cfg = config.get("chart_type", "auto")

    df = ctx.get("_last_df")
    summary_text = ctx.get("output", "No summary available.")

    try:
        from report_generator.pdf_builder import build_pdf
        png_path = None

        if include_chart and df is not None and not (hasattr(df, "empty") and df.empty):
            from report_generator.chart_selector import select_chart_type
            from report_generator.chart_builder import build_chart

            ct = chart_type_cfg if chart_type_cfg != "auto" else None
            if not ct:
                ct, _ = select_chart_type(df, title)
            _, png_path = build_chart(df, ct, title)

        from datetime import datetime
        insights = [
            f"Report generated by workflow: {ctx.get('_workflow_name', 'Unknown')}",
            f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"Data rows: {len(df) if df is not None else 'N/A'}",
        ]

        pdf_path = build_pdf(
            title=title,
            executive_summary=summary_text,
            dataframe=df,
            chart_image_path=png_path,
            key_insights=insights,
        )
        ctx["output"] = f"Report generated: {pdf_path}"
        ctx["_pdf_path"] = pdf_path
        logger.info(f"[AI] generate_report → {pdf_path}")

    except Exception as e:
        ctx["output"] = f"Report generation failed: {e}"
        logger.error(f"[AI] generate_report error: {e}")

    return ctx


def run_classify(config: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:
    categories = [c.strip() for c in config.get("categories", "positive, negative, neutral").split(",")]
    field = config.get("field", "text")
    data = str(ctx.get("output", ""))

    cat_list = ", ".join(categories)
    prompt = (
        f"Classify the following into exactly one of: {cat_list}\n\n"
        f"Input: {data[:2000]}\n\n"
        f"Reply with ONLY the category name, nothing else."
    )

    try:
        from config.llm_config import get_llm
        llm = get_llm()
        result = llm.invoke(prompt).strip()
        # Validate against known categories
        matched = next((c for c in categories if c.lower() in result.lower()), result)
        ctx["output"] = matched
        ctx["_classification"] = matched
        logger.info(f"[AI] classify → {matched}")
    except Exception as e:
        ctx["output"] = f"Classify error: {e}"

    return ctx
