"""Conversation Export — export chat history as Markdown or PDF."""
from __future__ import annotations
from datetime import datetime
from pathlib import Path
from config.settings import OUTPUTS_DIR

def to_markdown(messages, title=None):
    if not title: title = f"NexusAgent Conversation - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    lines = [f"# {title}", "", f"*Exported on {datetime.now().strftime('%B %d, %Y at %H:%M')}*", f"*{len(messages)} messages*", "", "---", ""]
    for msg in messages:
        role = msg.get("role", "user"); content = msg.get("content", ""); tools = msg.get("tools_used", [])
        ts = msg.get("timestamp", "")
        if role == "user": lines.append(f"## You {f'({ts})' if ts else ''}")
        else: lines.append(f"## NexusAgent {f'({ts})' if ts else ''}")
        lines.extend(["", content])
        if tools: lines.extend(["", f"**Tools used:** {', '.join(tools)}"])
        if msg.get("sources_used"):
            lines.extend(["", "**Sources:**"] + [f"- {s}" for s in msg["sources_used"]])
        lines.extend(["", "---", ""])
    lines.append("*Generated by NexusAgent | 100% Local AI*")
    return "\n".join(lines)

def save_markdown(messages, title=None):
    md = to_markdown(messages, title)
    out_dir = Path(OUTPUTS_DIR) / "exports"; out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"conversation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    path.write_text(md, encoding="utf-8"); return str(path)

def to_pdf(messages, title=None):
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    if not title: title = "NexusAgent Conversation"
    out_dir = Path(OUTPUTS_DIR) / "exports"; out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"conversation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(str(path), pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    blue = colors.HexColor("#1e3a5f"); grey = colors.HexColor("#64748b")
    title_style = ParagraphStyle("T", parent=styles["Title"], textColor=blue, fontSize=18)
    body_style = ParagraphStyle("B", parent=styles["BodyText"], fontSize=10, spaceAfter=6)
    meta_style = ParagraphStyle("M", parent=styles["Normal"], textColor=grey, fontSize=8, spaceAfter=4)
    role_style = ParagraphStyle("R", parent=styles["Heading4"], textColor=blue, fontSize=10, spaceAfter=2)
    story = [Paragraph(title, title_style), Paragraph(f"Exported {datetime.now().strftime('%B %d, %Y')} | {len(messages)} messages", meta_style),
             Spacer(1, 0.3*cm), HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")), Spacer(1, 0.3*cm)]
    for msg in messages:
        role = msg.get("role","user"); content = msg.get("content",""); ts = msg.get("timestamp","")
        label = f"You ({ts})" if role == "user" else f"NexusAgent ({ts})"
        story.append(Paragraph(label, role_style))
        safe = content.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
        story.append(Paragraph(safe, body_style))
        if msg.get("tools_used"): story.append(Paragraph(f"Tools: {', '.join(msg['tools_used'])}", meta_style))
        story.extend([Spacer(1, 0.2*cm), HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0")), Spacer(1, 0.2*cm)])
    story.append(Paragraph("Generated by NexusAgent", meta_style))
    doc.build(story); return str(path)
