"""Conversation Export — export chat history as Markdown or PDF."""
from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from config.settings import OUTPUTS_DIR


def to_markdown(messages, title=None):
    if not title:
        title = f"NexusAgent Conversation - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    lines = [
        f"# {title}", "",
        f"*Exported on {datetime.now().strftime('%B %d, %Y at %H:%M')}*",
        f"*{len(messages)} messages*",
        "", "---", "",
    ]
    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        tools = msg.get("tools_used", [])
        ts = msg.get("timestamp", "")
        if role == "user":
            lines.append(f"## You {f'({ts})' if ts else ''}")
        else:
            lines.append(f"## NexusAgent {f'({ts})' if ts else ''}")
        lines.extend(["", content])
        if tools:
            lines.extend(["", f"**Tools used:** {', '.join(tools)}"])
        if msg.get("sources_used"):
            lines.extend(["", "**Sources:**"] + [f"- {s}" for s in msg["sources_used"]])
        lines.extend(["", "---", ""])
    lines.append("*Generated by NexusAgent | 100% Local AI*")
    return "\n".join(lines)


def save_markdown(messages, title=None):
    md = to_markdown(messages, title)
    out_dir = Path(OUTPUTS_DIR) / "exports"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"conversation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    path.write_text(md, encoding="utf-8")
    return str(path)


# ── Markdown → ReportLab inline markup ──────────────────────────────────────
# ReportLab's Paragraph supports a subset of HTML (<b>, <i>, <br/>, <font>).
# The previous version dumped raw markdown which surfaced as literal
# **asterisks** in the PDF and ran every paragraph into one block.
def _md_inline_to_rl(text: str) -> str:
    """Bold/italic/code/links → ReportLab inline tags. HTML-escape first."""
    s = (text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Bold (must run before italic since ** would match)
    s = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", s)
    s = re.sub(r"__(.+?)__", r"<b>\1</b>", s)
    # Italic
    s = re.sub(r"(?<!\*)\*(?!\*)([^*\n]+?)(?<!\*)\*(?!\*)", r"<i>\1</i>", s)
    # Inline code → monospace + grey background marker (ReportLab doesn't
    # support background but we can use font face).
    s = re.sub(r"`([^`]+)`", r"<font face='Courier' color='#3b3b3b'>\1</font>", s)
    # Markdown links [text](url) → underline + keep text (URL appended in parens)
    s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"<u>\1</u> (\2)", s)
    return s


def _md_block_to_flowables(text: str, body_style, bullet_style):
    """Split a message body into Paragraph flowables, handling lists, headings,
    code blocks, and blank-line paragraph separation."""
    from reportlab.platypus import Paragraph, Spacer
    from reportlab.lib.units import cm
    out = []
    if not text:
        return out
    # Strip ``` code fences but keep their content as monospace.
    text = re.sub(r"```[a-zA-Z0-9]*\n", "", text)
    text = text.replace("```", "")
    paragraph_buf = []

    def flush_paragraph():
        if not paragraph_buf:
            return
        joined = " ".join(paragraph_buf).strip()
        paragraph_buf.clear()
        if joined:
            out.append(Paragraph(_md_inline_to_rl(joined), body_style))

    for raw_line in text.split("\n"):
        line = raw_line.rstrip()
        # Headings — render bold + slightly larger via style param tweak.
        m_head = re.match(r"^(#{1,6})\s+(.+)$", line)
        if m_head:
            flush_paragraph()
            out.append(Paragraph(f"<b>{_md_inline_to_rl(m_head.group(2))}</b>", body_style))
            continue
        # Bullet list
        m_bullet = re.match(r"^\s*[-*+]\s+(.+)$", line)
        if m_bullet:
            flush_paragraph()
            out.append(Paragraph(f"•  {_md_inline_to_rl(m_bullet.group(1))}", bullet_style))
            continue
        # Numbered list
        m_num = re.match(r"^\s*(\d+)\.\s+(.+)$", line)
        if m_num:
            flush_paragraph()
            out.append(Paragraph(f"{m_num.group(1)}.  {_md_inline_to_rl(m_num.group(2))}", bullet_style))
            continue
        # Blockquote
        m_quote = re.match(r"^\s*>\s?(.*)$", line)
        if m_quote:
            flush_paragraph()
            out.append(Paragraph(f"<i>{_md_inline_to_rl(m_quote.group(1))}</i>", bullet_style))
            continue
        # Blank line → paragraph break
        if not line.strip():
            flush_paragraph()
            out.append(Spacer(1, 0.15 * cm))
            continue
        # Regular line — accumulate until blank line.
        paragraph_buf.append(line)
    flush_paragraph()
    return out


def to_pdf(messages, title=None):
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle,
    )

    if not title:
        title = "NexusAgent Conversation"
    out_dir = Path(OUTPUTS_DIR) / "exports"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"conversation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    doc = SimpleDocTemplate(
        str(path), pagesize=A4,
        rightMargin=2 * cm, leftMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()

    # Palette — soft contrast, easy to read printed.
    brand = colors.HexColor("#0f766e")        # NexusAgent green
    user_bg = colors.HexColor("#e6fffb")      # very light teal
    agent_bg = colors.HexColor("#f4f6f8")     # very light grey
    text_dark = colors.HexColor("#1e293b")
    text_muted = colors.HexColor("#64748b")
    rule = colors.HexColor("#e2e8f0")

    title_style = ParagraphStyle(
        "T", parent=styles["Title"], textColor=brand,
        fontSize=18, spaceAfter=4, alignment=0,
    )
    meta_style = ParagraphStyle(
        "M", parent=styles["Normal"], textColor=text_muted,
        fontSize=8, spaceAfter=4,
    )
    role_user_style = ParagraphStyle(
        "RU", parent=styles["Normal"], textColor=brand,
        fontSize=9, fontName="Helvetica-Bold", spaceAfter=4,
    )
    role_agent_style = ParagraphStyle(
        "RA", parent=styles["Normal"], textColor=colors.HexColor("#3730a3"),
        fontSize=9, fontName="Helvetica-Bold", spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "B", parent=styles["BodyText"], textColor=text_dark,
        fontSize=10, leading=14, spaceAfter=4,
    )
    bullet_style = ParagraphStyle(
        "Bullet", parent=body_style,
        leftIndent=12, spaceAfter=2, leading=14,
    )

    story = [
        Paragraph(title, title_style),
        Paragraph(
            f"Exported {datetime.now().strftime('%B %d, %Y at %H:%M')}  ·  "
            f"{len(messages)} message{'s' if len(messages) != 1 else ''}",
            meta_style,
        ),
        Spacer(1, 0.3 * cm),
        HRFlowable(width="100%", thickness=1, color=rule),
        Spacer(1, 0.4 * cm),
    ]

    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        ts = msg.get("timestamp", "")
        is_user = role == "user"
        label = f"You{' · ' + ts if ts else ''}" if is_user else f"NexusAgent{' · ' + ts if ts else ''}"
        role_style = role_user_style if is_user else role_agent_style
        bg = user_bg if is_user else agent_bg

        # Build the per-message contents (label + rendered body) as a
        # one-column table so we can give it a subtle background tint —
        # makes user vs agent visually distinct without colored bubbles.
        cell_flows = [Paragraph(label, role_style)]
        cell_flows.extend(_md_block_to_flowables(content, body_style, bullet_style))
        tools = msg.get("tools_used") or []
        # Deduplicate tools_used the same way the chat UI does.
        seen, dedup_tools = set(), []
        for t in tools:
            if t and t not in seen:
                seen.add(t)
                dedup_tools.append(t)
        if dedup_tools:
            cell_flows.append(Spacer(1, 0.1 * cm))
            cell_flows.append(Paragraph(
                f"<i>Tools: {', '.join(dedup_tools)}</i>",
                ParagraphStyle("ToolMeta", parent=meta_style, fontSize=8),
            ))

        msg_table = Table([[cell_flows]], colWidths=[doc.width])
        msg_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), bg),
            ("BOX", (0, 0), (-1, -1), 0.4, rule),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(msg_table)
        story.append(Spacer(1, 0.3 * cm))

    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=rule))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(
        "Generated by NexusAgent  ·  nexusagent.in",
        meta_style,
    ))

    doc.build(story)
    return str(path)
