"""
Conversation Export — export chat history as Markdown or PDF.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any

from loguru import logger

from config.settings import OUTPUTS_DIR


def to_markdown(messages: List[Dict[str, Any]], title: str = None) -> str:
    """Export conversation to formatted Markdown string."""
    if not title:
        title = f"NexusAgent Conversation - {datetime.now().strftime('%Y-%m-%d %H:%M')}"

    lines = [
        f"# {title}",
        "",
        f"*Exported on {datetime.now().strftime('%B %d, %Y at %H:%M')}*",
        f"*{len(messages)} messages*",
        "",
        "---",
        "",
    ]

    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        tools = msg.get("tools_used", [])
        sources = msg.get("sources_used", [])
        citations = msg.get("citations", [])
        multi_agent = msg.get("multi_agent", False)
        agents = msg.get("agents_used", [])
        timestamp = msg.get("timestamp", "")

        if role == "user":
            lines.append(f"## You {f'({timestamp})' if timestamp else ''}")
            lines.append("")
            lines.append(content)
        else:
            lines.append(f"## NexusAgent {f'({timestamp})' if timestamp else ''}")
            lines.append("")
            lines.append(content)

            # Metadata
            if tools:
                lines.append("")
                lines.append(f"**Tools used:** {', '.join(tools)}")

            if multi_agent and agents:
                agent_labels = ", ".join(a.replace("Agent", "") for a in agents)
                lines.append(f"**Multi-Agent Collaboration:** {agent_labels}")

            if sources:
                lines.append("")
                lines.append("**Sources:**")
                for src in sources:
                    lines.append(f"- {src}")

            if citations:
                lines.append("")
                lines.append("**Citations:**")
                for c in citations:
                    conf = c.get("confidence", 0)
                    lines.append(
                        f"- {c.get('source', '?')} (Page {c.get('page', '?')}, "
                        f"confidence: {conf:.0%})"
                    )

        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append(f"*Generated by NexusAgent | 100% Local AI*")
    return "\n".join(lines)


def save_markdown(messages: List[Dict[str, Any]], title: str = None) -> str:
    """Save conversation to a Markdown file. Returns file path."""
    md = to_markdown(messages, title)
    out_dir = Path(OUTPUTS_DIR) / "exports"
    out_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"conversation_{timestamp}.md"
    path = out_dir / filename
    path.write_text(md, encoding="utf-8")

    logger.info(f"[Export] Markdown saved: {path}")
    return str(path)


def to_pdf(messages: List[Dict[str, Any]], title: str = None) -> str:
    """Export conversation to PDF. Returns file path."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
        )
    except ImportError:
        logger.error("[Export] ReportLab not installed")
        return ""

    if not title:
        title = f"NexusAgent Conversation"

    out_dir = Path(OUTPUTS_DIR) / "exports"
    out_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"conversation_{timestamp}.pdf"
    path = out_dir / filename

    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    blue = colors.HexColor("#1e3a5f")
    accent = colors.HexColor("#3b82f6")
    grey = colors.HexColor("#64748b")

    title_style = ParagraphStyle(
        "ConvTitle", parent=styles["Title"], textColor=blue, fontSize=18,
    )
    user_style = ParagraphStyle(
        "UserMsg", parent=styles["BodyText"],
        textColor=colors.HexColor("#1e293b"),
        fontSize=10, spaceAfter=6,
        leftIndent=10,
        borderColor=accent, borderWidth=2, borderPadding=8,
    )
    assistant_style = ParagraphStyle(
        "AssistantMsg", parent=styles["BodyText"],
        textColor=colors.HexColor("#0f172a"),
        fontSize=10, spaceAfter=6,
        leftIndent=10,
    )
    meta_style = ParagraphStyle(
        "Meta", parent=styles["Normal"],
        textColor=grey, fontSize=8, spaceAfter=4,
    )
    role_style = ParagraphStyle(
        "RoleLabel", parent=styles["Heading4"],
        textColor=blue, fontSize=10, spaceAfter=2,
    )

    story = []
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(
        f"Exported on {datetime.now().strftime('%B %d, %Y at %H:%M')} | "
        f"{len(messages)} messages",
        meta_style,
    ))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    story.append(Spacer(1, 0.3 * cm))

    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        tools = msg.get("tools_used", [])
        timestamp_str = msg.get("timestamp", "")

        if role == "user":
            label = f"You {f'({timestamp_str})' if timestamp_str else ''}"
            story.append(Paragraph(label, role_style))
            # Sanitize content for ReportLab (escape XML)
            safe_content = (
                content.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            story.append(Paragraph(safe_content, user_style))
        else:
            label = f"NexusAgent {f'({timestamp_str})' if timestamp_str else ''}"
            story.append(Paragraph(label, role_style))
            safe_content = (
                content.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            story.append(Paragraph(safe_content, assistant_style))

            if tools:
                story.append(Paragraph(
                    f"Tools: {', '.join(tools)}",
                    meta_style,
                ))

        story.append(Spacer(1, 0.2 * cm))
        story.append(HRFlowable(
            width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"),
        ))
        story.append(Spacer(1, 0.2 * cm))

    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph("Generated by NexusAgent | 100% Local AI", meta_style))

    doc.build(story)
    logger.info(f"[Export] PDF saved: {path}")
    return str(path)
